sonar.projectKey=jhssic-iblueit-clinical-reports
sonar.organization=jhssic

sonar.sources=iblueit-health-Infocharts/src,iblueit-server-side
sonar.exclusions=**/node_modules/**,**/venv/**,**/__pycache__/**,**/build/**,**/*.test.js,**/coverage/**

sonar.sourceEncoding=UTF-8
